<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>razorctl</AssemblyName>
    <RootNamespace>Razor.Cli</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>sagas_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\external\AssistantApi\src\UOSagas.AssistantApi\UOSagas.AssistantApi.csproj" />
  </ItemGroup>

</Project>
