#region license
// UOSagas Razor: An Ultima Online Assistant for the UOSagas shard
// Copyright (C) 2026 UOSagas (3HMonkey)
//
// Based on Razor: An Ultima Online Assistant
// Copyright (c) 2022 Razor Development Community on GitHub <https://github.com/markdwags/Razor>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
#endregion

// UOSagas-Razor: Assistant.Language / LocString aus Razor CE.
//
// Phase 3c: Die LocString-Werte sind jetzt EXAKT die numerischen Werte aus
// Razor CE (Razor/UI/Languages.cs) — das ist zwingend fuer die Profil-
// Kompatibilitaet der hotkeys-Sektion: Razor CE speichert loc-registrierte
// Hotkeys als "L:<locid>" (z. B. "L:1058" fuer Last Target). Alte CE-Profile
// muessen auf dieselben Registrierungen mappen.
//
// Language selbst bleibt ein schlanker Ersatz: Statt der Language-Packs haelt
// eine eingebettete ENU-Tabelle die Texte, die fuer Hotkey-IDENTITAET
// (string-registrierte Hotkeys wie "Play: {0}" oder "Set Sell HotBag" werden
// mit dem englischen Text in der Profil-XML gespeichert!) und fuer die
// Anzeige gebraucht werden. Fuer alle anderen Schluessel faellt GetString auf
// den Enum-Namen zurueck (reine Anzeige-Strings, keine Serialisierung).

using System;
using System.Collections.Generic;

namespace Assistant
{
    /// <summary>
    /// LocString-Schluessel aus Razor CE (Razor/UI/Languages.cs) — Werte
    /// 1:1 uebernommen (Profil-Kompatibilitaet der "L:&lt;id&gt;"-Hotkey-Namen).
    /// </summary>
    public enum LocString : int
    {
        Null = 0,

        __Start = 1000,
        DeathStatus,
        BardMusic,
        DogSounds,
        CatSounds,
        HorseSounds,
        SheepSounds,
        SS_Sound,
        FizzleSound,
        Weather,
        DispCounters,
        RecountCounters,
        ClearAbility,
        SetPrimAb,
        SetSecAb,
        ToggleStun,
        ToggleDisarm,
        SettingAOSAb,
        AOSAbCleared,
        UndressAll,
        UndressHands,
        UndressLeft,
        UndressRight,
        UndressHat,
        UndressJewels,
        BandageSelf,
        BandageLT,
        UseBandage,
        DrinkHeal,
        DrinkCure,
        DrinkRef,
        DrinkNS,
        DrinkExp,
        DrinkStr,
        DrinkAg,
        NoBandages,
        NoItemOfType,
        DClickA1,
        ReTarget,
        Conv2DCT,
        SelTargAct,
        ProfileLoadEx,
        MacroItemOutRange,
        LiftA10,
        ConvLiftByType,
        MacroNoHold,
        EquipTo,
        DropA2,
        ConvRelLoc,
        DropRelA3,
        GumpRespB, //1050
        CloseGump,
        MenuRespA1,
        MacroNoTarg,
        AbsTarg,
        ConvLT,
        ConvTargType,
        TargRelLocA3,
        LastTarget,
        TargetSelf,
        SetLT,
        TargRandRed,
        TargRandGrey,
        TargRandBlue,
        TargRandEnemy,
        TargRandFriend,
        TargRandNFriend,
        SayQA1,
        UseSkillA1,
        CastSpellA1,
        SetAbilityA1,
        DressA1,
        UndressA1,
        UndressLayerA1,
        WaitAnyMenu,
        WaitMenuA1,
        Edit,
        WaitAnyGump,
        WaitGumpA1,
        WaitTarg,
        PauseA1,
        WaitA3,
        LoadingA1,
        StopCurrent,
        PlayA1,
        PlayingA1,
        MacroFinished,
        InitError,
        IE_1,
        IE_2,
        IE_3,
        IE_4,
        IE_5,
        IE_6,
        IE_7,
        NoMemCpy,
        SkillChanged,
        InvalidAbrev,
        InvalidIID,
        InvalidHue,
        SelItem2Count, // 1100
        ProfileCorrupt,
        NoProp,
        CounterFux,
        NoAutoCount,
        CountLow,
        SelHue,
        TakeSS,
        TitleBarTip,
        RazorStatus1,
        SetSLUp,
        SetSLDown,
        SetSLLocked,
        ConfirmDelCounter,
        ProfLoadQ,
        ProfLoadE,
        NoDelete,
        EnterProfileName,
        ProfExists,
        DressName,
        DelDressQ,
        OutOfRangeA1,
        DelDressItemQ,
        TargUndressBag,
        UB_Set,
        ItemNotFound,
        KeyUsed,
        SaveOK,
        PacketLogWarn,
        Conv2Type,
        NewMacro,
        InvalidChars,
        MacroExists,
        MacroConfRec,
        DelConf,
        InsWait,
        InsLT,
        MoveUp,
        MoveDown,
        RemAct,
        BeginRec,
        FileNotFoundA1,
        Confirm,
        FileDelError,
        NextRestart,
        PWWarn,
        NeedPort,
        QueueIgnore,
        ActQueued,
        QueueFinished,
        UseOnceAgent, // 1150
        AddTarg,
        AddContTarg,
        RemoveTarg,
        ClearList,
        TargItemAdd,
        TargCont,
        TargItemRem,
        ItemAdded,
        ItemRemoved,
        ItemsAdded,
        UseOnceEmpty,
        UseOnceStatus,
        UseOnceError,
        SellTotals,
        Remove,
        ContSet,
        Clear,
        PushDisable,
        PushEnable,
        SetHB,
        ClearHB,
        OrganizerAgent,
        Organizer,
        OrganizeNow,
        ContNotSet,
        NoBackpack,
        OrgQueued,
        OrgNoItems,
        ItemExists,
        AutoSearchEx,
        BuyTotals,
        BuyLowGold,
        EnterAmount,
        PrioSet,
        CurTime,
        CurLoc,
        UndressBagRange,
        UndressQueued,
        DressQueued,
        AlreadyDressed,
        ItemsNotFound,
        NoSpells,
        StealthSteps,
        StealthStart,
        ClearTargQueue,
        AttackLastComb,
        TQCleared,
        TargSetLT,
        LTSet,
        NewTargSet, // 1200
        TargNoOne,
        QueuedTS,
        QueuedLT,
        OTTCancel,
        TargByType,
        Scavenger,
        DeleteConfirm,
        SelSSFolder,
        HotKeys,

        // 1210 - 1248 reserviert fuer Hotkey-Kategorien
        HKSubOffset = 1249,
        // 1252 - 1300 reserviert fuer Hotkey-Unterkategorien

        Sell = 1301,
        Buy,
        InputReq,
        CommandList,
        UseHand,
        MustDisarm,
        ArmDisarmRight,
        ArmDisarmLeft,
        DropCur,
        SpellWeaving,
        ToggleHKEnable,
        HKEnabledPress,
        HKDisabledPress,
        HKEnabled,
        HKDisabled,
        WalkA1,
        AddTargType,
        LTOutOfRange,
        SellAmount,
        SnoopFilter,
        PackSound,
        InsIF,
        InsELSE,
        InsENDIF,
        SetAmt,
        Restock,
        RestockNow,
        RestockAgent,
        RestockTarget,
        InvalidCont,
        RestockDone,
        CancelTarget,
        NewerVersion,
        Reload,
        Save,
        LTGround,
        Resync,
        DismountBlocked,
        RecStart,
        VidStop,
        RecError,
        WrongVer,
        VideoCorrupt,
        ReadError,
        CatName,
        CantDelDir,
        CanCreateDir,
        CantMoveMacro,
        Friends,

        // 1350 - 1359 reserviert fuer PacketPlayer-Stop-Meldungen
        Reserved0 = 1350,
        Reserved1 = 1359,

        TargFriendAdd,
        TargFriendRem,
        FriendAdded,
        FriendRemoved,
        Constructs,
        InsFOR,
        InsENDFOR,
        NumIter,
        ClearScavCache,
        LastSpell,
        LastSkill,
        LastObj,
        AllNames,
        UseOnce,
        TargRandEnemyHuman,
        TargRandGreyHuman,
        TargRandInnocentHuman,
        TargRandCriminalHuman,
        TargRandCriminal,
        ForceEndHolding,
        RestartClient,
        ApplyOptionsRequired,
        LiftQueued,
        RestockQueued,
        StrChanged,
        DexChanged,
        IntChanged,
        LightFilter,
        HealPoisonBlocked,
        ClearDragDropQueue,
        StopNow,
        HealOrCureSelf,
        NextTarget,
        SetRestockHB,
        AddUseOnce,
        AttackLastTarg,
        EditTimeout,
        NoHold,
        NotAllowed,
        Allowed,

        // 1400 - 1465 reserviert fuer Negotiation-Features
        NegotiateTitle = 1400,
        AllFeaturesEnabled,
        FeatureDescBase,

        NextCliloc = 1466,
        FeatureDisabled = NextCliloc,
        FeatureDisabledText,
        InsComment,
        AddFriend,
        RemoveFriend,
        MiniHealOrCureSelf,
        NoPatchWarning,
        Dismount,
        ToggleMap,
        TooFar,
        DragDropQueueFull,
        ToggleWarPeace,
        VetRewardGump,
        ForceSizeBad,
        ScavengerHB,
        RestockHBA1,
        UseOnceHBA1,
        SellHB,
        OrganizerHBA1,
        BadServerAddr,
        PartyAccept,
        PartyDecline,
        HarmfulTarget,
        BeneficialTarget,
        RazorFriend,
        PlayFromHere,
        Initializing,
        LoadingLastProfile,
        LoadingClient,
        WaitingForClient,
        RememberDonate,
        Welcome,
        Auto2D,
        Auto3D,
        AutoDetect, // 1500
        OpacityA1,
        NewTimeout,
        NotAssigned,
        ChangeTimeout,
        EnterAName,
        Invalid,
        StaffOnlyItems,
        sStatsA1,
        DrinkApple,

        TargCloseRed,
        TargCloseGrey,
        TargCloseBlue,
        TargCloseEnemy,
        TargCloseFriend,
        TargCloseNFriend,
        TargCloseEnemyHuman,
        TargCloseGreyHuman,
        TargCloseInnocentHuman,
        TargCloseCriminalHuman,
        TargCloseCriminal,

        ProfileInUse,
        WaitingTimeout,
        NoCliLocMsg,
        NoCliLoc,
        BOD,
        LaunchBODAgent,

        NextTargetHumanoid,
        NewClipboardMacro = 1950,
        CopyClipboardMacro = 1951,
        DeerSounds,
        MacroRename,
        NewMacroVariable,

        TargCloseGreyMonster,
        TargCloseEnemyMonster,
        TargRandGreyMonster,
        TargRandEnemyMonster,
        CyclopTitanSounds,
        NextTargetEnemyHumanoid,
        UnableToOpenMacro,
        PauseCurrent,
        MacroPaused,
        MacroResuming,
        StunReady,
        StunSuccessful,
        StunDisabled,
        StunFailed,
        AllCorpses,
        AllMobiles,
        BullSounds,
        DragonSounds,
        SetSellAgentHotBag,
        AddUseOnceContainer,
        ChickenSounds,
        Reserved3,
        ScavengerEnableDisable,
        ScavengerSetHotBag,
        ScavengerAddTarget,
        GoldPerHotkey,
        EnterNewText,
        ImportFromPrevious,
        SetOrganizerHB,
        SetContainerLabel,
        AddToIgnore,
        RemoveFromIgnore,
        RazorIgnored,
        IgnoreAgent,
        PrevTarget,
        PrevTargetEnemyHumanoid,
        PrevTargetHumanoid,
        UseLastGumpResponse,
        SetContainerAlias,
        Interrupt,
        CaptureBod,
        DamageTracker,
        EnableHotkeys,
        DisableHotkeys,
        ClientDataMismatch,
        TargetRandom,
        TargCloseRedMonster,
        TargCloseRedHumanoid,
        TargClosest,
        TargRandomRedHuman,
        TargRandomRedMonster,
        TargRandomNFriendlyHuman,
        TargRandomNFriendlyMonster,
        TargRandomFriendlyHuman,
        TargRandomFriendlyMonster,
        TargRandomInnocentMonster,
        TargRandomCriminalMonster,
        TargClosestNFriendlyHuman,
        TargClosestNFriendlyMonster,
        TargClosestFriendlyHuman,
        TargClosestFriendlyMonster,
        TargClosestInnocentMonster,
        TargClosestCriminalMonster,
        NextTargetMonster,
        PrevTargetMonster,
        AddAllMobileFriends,
        AllCome,
        AllFollowMe,
        AllFollow,
        AllGuardMe,
        AllGuard,
        AllKill,
        AllStay,
        AllStop,
        PetCommands,
        Friend,
        StrChangeOverhead,
        DexChangeOverhead,
        IntChangeOverhead,
        SkillChangeOverhead,
        GrabItem,
        SetGrabItemHotBag,
        GrabItemTarget,
        GrabHB,
        NextTargetCriminalHumanoid,
        NextTargetMurdererHumanoid,
        NextTargetInnocentHumanoid,
        PrevTargetCriminalHumanoid,
        PrevTargetMurdererHumanoid,
        PrevTargetInnocentHumanoid,
        CriminalTargets,
        EnemyTargets,
        FriendlyTargets,
        GreyTargets,
        InnocentTargets,
        MurdererTargets,
        NonFriendlyTargets,
        NextTargetFriendlyHumanoid,
        NextTargetGreyHumanoid,
        NextTargetNonFriendlyHumanoid,
        PrevTargetFriendlyHumanoid,
        PrevTargetGreyHumanoid,
        PrevTargetNonFriendlyHumanoid,
        ToggleWar,
        TogglePeace,
        GHealOrCureSelf,
        SetLastBeneficial,
        SetLastHarmful,
        SetLTBene,
        SetLTHarm,
        TargClosestFriend,
        TargRandomFriend,
        NextTargetFriend,
        PrevTargetFriend,
        UseRightHand,
        UseLeftHand,
        InsertOverheadMessage,
        InsertWaitForTarget,
        AddAllHumanoidsAsFriends,
        NextTargetEnemyMonster,
        NextTargetCriminalMonster,
        NextTargetMurdererMonster,
        NextTargetInnocentMonster,
        PrevTargetCriminalMonster,
        PrevTargetMurdererMonster,
        PrevTargetInnocentMonster,
        NextTargetFriendlyMonster,
        NextTargetGreyMonster,
        NextTargetNonFriendlyMonster,
        PrevTargetEnemyMonster,
        PrevTargetFriendlyMonster,
        PrevTargetGreyMonster,
        PrevTargetNonFriendlyMonster,
        NewBeneficialTarget,
        NewHarmfulTarget,
        BirdSounds,
        AddAllMobilesTargetFilter,
        AddAllMobilesHumanoidTargetFilter,
        InsertWhile,
        InsertEndWhile,
        InsertDo,
        InsertDoWhile,
        PlayScript,
        NewScriptVariable,
        ScriptPlaying,
        ScriptFinished,
        StopScript,
        PartyAdd,
        Mysticism,
        Masteries,
        NextWaypoint,
        PrevWaypoint,
        HideWaypoint,
        InsertClearSysMsg,
        ClearSysMsg,
        NextTargetNonFriendly,
        PrevTargetNonFriendly,
        SetHue,
        ScriptDClickType,
        ScriptTargetType,
        ScriptCopied,
        GumpInfo,
        GumpSysMsg,
        GumpHotKeys,
        GumpBoatControl,
        BuyAgentAttempt,
        NextTargetFriendly,
        PrevTargetFriendly,
        PauseScript,
        ResumeScriptMessage,
        PauseScriptMessage,
        ScriptFinishedStopwatch,
        __End
    }

    /// <summary>
    /// Schlanker Language-Ersatz: eingebettete ENU-Teilmenge (Hotkey-Namen,
    /// Kategorien, Status-Texte) mit Fallback auf den Enum-Namen.
    /// </summary>
    public static class Language
    {
        /// <summary>Razor CE: Sprachkuerzel der Cliloc-Datei (fuer 0xAE-Injections).</summary>
        public static string CliLocName = "ENU";

        // Teilmenge aus Razor CE etc/Language/Razor_lang.enu. Die Texte der
        // string-registrierten Hotkeys (Play/Organizer/Restock/Sell) sind
        // IDENTITAETSSTIFTEND (landen woertlich in der Profil-XML) und muessen
        // exakt dem CE-Original entsprechen.
        private static readonly Dictionary<int, string> m_Enu = new Dictionary<int, string>
        {
            // Dress/Undress
            [(int) LocString.UndressAll] = "Undress All",
            [(int) LocString.UndressHands] = "Undress Both Hands",
            [(int) LocString.UndressLeft] = "Undress Left Hand",
            [(int) LocString.UndressRight] = "Undress Right Hand",
            [(int) LocString.UndressHat] = "Undress Hat",
            [(int) LocString.UndressJewels] = "Undress Jewelry",
            [(int) LocString.ArmDisarmRight] = "Arm/Disarm Right Hand",
            [(int) LocString.ArmDisarmLeft] = "Arm/Disarm Left Hand",

            // Targets
            [(int) LocString.LastTarget] = "Last Target",
            [(int) LocString.TargetSelf] = "Target Self",
            [(int) LocString.SetLT] = "Set Last Target",
            [(int) LocString.ClearTargQueue] = "Clear Target Queue",
            [(int) LocString.CancelTarget] = "Cancel Current Target",
            [(int) LocString.TQCleared] = "Target queue cleared.",
            [(int) LocString.TargSetLT] = "Target a new 'Last Target'",
            [(int) LocString.LTSet] = "Last Target set.",

            // SmartLastTarget (CE 2061-2064, 2088/2089, 1488/1489)
            [(int) LocString.SetLastBeneficial] = "Set Last Target (Beneficial)",
            [(int) LocString.SetLastHarmful] = "Set Last Target (Harmful)",
            [(int) LocString.SetLTBene] = "Last Beneficial Target Set",
            [(int) LocString.SetLTHarm] = "Last Harmful Target Set",
            [(int) LocString.NewBeneficialTarget] = "Target a new 'Beneficial Target'",
            [(int) LocString.NewHarmfulTarget] = "Target a new 'Harmful Target'",
            [(int) LocString.HarmfulTarget] = "Harmful Target",
            [(int) LocString.BeneficialTarget] = "Beneficial Target",

            // Macros
            [(int) LocString.StopCurrent] = "> Stop Current Macro",
            [(int) LocString.PauseCurrent] = "> Pause Current Macro",
            [(int) LocString.PlayA1] = "Play: {0}",

            // Agents
            [(int) LocString.UseOnceAgent] = "Use Once Agent",
            [(int) LocString.AddUseOnce] = "Add to UseOnce",
            [(int) LocString.AddUseOnceContainer] = "Add UseOnce Container",
            [(int) LocString.OrganizerAgent] = "Organizer Agent",
            [(int) LocString.SetOrganizerHB] = "Set Organizer HotBag",
            [(int) LocString.RestockAgent] = "Restock Agent",
            [(int) LocString.SetRestockHB] = "Set Restock HotBag",
            [(int) LocString.ClearScavCache] = "Clear Scavenger Cache",
            [(int) LocString.ScavengerEnableDisable] = "Scavenger Enable/Disable",
            [(int) LocString.ScavengerSetHotBag] = "Scavenger Set Hot Bag",
            [(int) LocString.ScavengerAddTarget] = "Scavenger Add Target",
            [(int) LocString.SetSellAgentHotBag] = "Set Sell HotBag",
            [(int) LocString.AddToIgnore] = "Add to ignore list",
            [(int) LocString.RemoveFromIgnore] = "Remove from ignore list",

            // HotKey-System / Status
            [(int) LocString.ToggleHKEnable] = "> Enable/Disable Razor HotKeys",
            [(int) LocString.EnableHotkeys] = ">> Enable Razor HotKeys",
            [(int) LocString.DisableHotkeys] = ">> Disable Razor HotKeys",
            [(int) LocString.HKEnabledPress] = "Hot Keys Enabled (Press {0} to disable)",
            [(int) LocString.HKDisabledPress] = "Hot Keys Disabled (Press {0} to enable)",
            [(int) LocString.HKEnabled] = "Hot Keys Enabled",
            [(int) LocString.HKDisabled] = "Hot Keys Disabled",
            [(int) LocString.NotAssigned] = "not assigned",

            // Phase 3c2: Texte der neu registrierten Hotkeys (generiert aus
            // Razor CE etc/Language/Razor_lang.enu, IDs siehe UI/Languages.cs).
            [(int) LocString.DispCounters] = "Display Counters",
            [(int) LocString.RecountCounters] = "Recount Counters",
            [(int) LocString.ClearAbility] = "Clear AOS Ability",
            [(int) LocString.SetPrimAb] = "Set Primary Ability (AOS)",
            [(int) LocString.SetSecAb] = "Set Secondary Ability (AOS)",
            [(int) LocString.ToggleStun] = "Toggle Stun (Pre-AOS)",
            [(int) LocString.ToggleDisarm] = "Toggle Disarm (Pre-AOS)",
            [(int) LocString.SettingAOSAb] = "Setting ability {0}",
            [(int) LocString.AOSAbCleared] = "AOS Abilities cleared.",
            [(int) LocString.ToggleWarPeace] = "Toggle War/Peace",
            [(int) LocString.ToggleWar] = "Toggle War Only",
            [(int) LocString.TogglePeace] = "Toggle Peace Only",
            [(int) LocString.BandageSelf] = "Bandage Self",
            [(int) LocString.BandageLT] = "Bandage LastTarget",
            [(int) LocString.UseBandage] = "Use Bandage (No Timer)",
            [(int) LocString.DrinkHeal] = "Drink Heal",
            [(int) LocString.DrinkCure] = "Drink Cure",
            [(int) LocString.DrinkRef] = "Drink Refresh",
            [(int) LocString.DrinkNS] = "Drink Night Sight",
            [(int) LocString.DrinkExp] = "Drink Explosion",
            [(int) LocString.DrinkStr] = "Drink Strength",
            [(int) LocString.DrinkAg] = "Drink Agility",
            [(int) LocString.DrinkApple] = "Eat Enchanted Apple",
            [(int) LocString.NoBandages] = "No bandages found",
            [(int) LocString.NoItemOfType] = "No item of type {0} found!",
            [(int) LocString.UseHand] = "Use Item in Hand",
            [(int) LocString.UseRightHand] = "Use Item in Right Hand",
            [(int) LocString.UseLeftHand] = "Use Item in Left Hand",
            [(int) LocString.HealPoisonBlocked] = "Heal blocked (the target is poisoned)!",
            [(int) LocString.GrabItem] = "Grab Item",
            [(int) LocString.SetGrabItemHotBag] = "Set Grab Item HotBag",
            [(int) LocString.GrabItemTarget] = "Target item to grab",
            [(int) LocString.GrabHB] = "(Grab Item HotBag)",
            [(int) LocString.Dismount] = "Dismount",
            [(int) LocString.Resync] = "Resynchronize Client",
            [(int) LocString.LastSpell] = "Last Spell",
            [(int) LocString.LastSkill] = "Last Skill",
            [(int) LocString.LastObj] = "Last Object",
            [(int) LocString.AllNames] = "All Names",
            [(int) LocString.AllCorpses] = "All Corpses",
            [(int) LocString.AllMobiles] = "All Mobiles",
            [(int) LocString.PartyAccept] = "Party: Accept Invitation",
            [(int) LocString.PartyDecline] = "Party: Decline Invitation",
            [(int) LocString.PartyAdd] = "Party: Add",
            [(int) LocString.DropCur] = "Drop What You are Currently Holding",
            [(int) LocString.ClearDragDropQueue] = "Clear Drag/Drop Queue",
            [(int) LocString.PetCommands] = "Pet Commands",
            [(int) LocString.AllCome] = "All Come",
            [(int) LocString.AllFollowMe] = "All Follow Me",
            [(int) LocString.AllFollow] = "All Follow",
            [(int) LocString.AllGuardMe] = "All Guard Me",
            [(int) LocString.AllGuard] = "All Guard",
            [(int) LocString.AllKill] = "All Kill",
            [(int) LocString.AllStay] = "All Stay",
            [(int) LocString.AllStop] = "All Stop",
            [(int) LocString.HealOrCureSelf] = "> Smart Heal/Cure Self",
            [(int) LocString.MiniHealOrCureSelf] = "> Mini-Heal/Cure Self",
            [(int) LocString.GHealOrCureSelf] = "> Greater Heal/Cure Self",
            [(int) LocString.Interrupt] = "> Interrupt",
            [(int) LocString.NoSpells] = "Warning: Spells.def not found, spell format text will not be shown",
            [(int) LocString.ClearTargQueue] = "Clear Target Queue",
            [(int) LocString.AttackLastComb] = "Attack Last Combatant",
            [(int) LocString.AttackLastTarg] = "Attack Last Target",
            [(int) LocString.TQCleared] = "Target queue cleared.",
            [(int) LocString.NewTargSet] = "New target set.",
            [(int) LocString.TargNoOne] = "No one matching that was found on your screen.",
            [(int) LocString.QueuedTS] = "Queued target self.",
            [(int) LocString.QueuedLT] = "Queued last target.",
            [(int) LocString.OTTCancel] = "Server sent new target, canceling Razor target.",
            [(int) LocString.TargetRandom] = "Target Random Mobile",
            [(int) LocString.TargClosest] = "Target Closest Mobile",
            [(int) LocString.NextTarget] = "Next Target",
            [(int) LocString.PrevTarget] = "Previous Target",
            [(int) LocString.NextTargetHumanoid] = "Next Humanoid Target",
            [(int) LocString.PrevTargetHumanoid] = "Previous Humanoid Target",
            [(int) LocString.NextTargetMonster] = "Next Monster Target",
            [(int) LocString.PrevTargetMonster] = "Previous Monster Target",
            [(int) LocString.NextTargetNonFriendly] = "Next Non-Friendly Target",
            [(int) LocString.PrevTargetNonFriendly] = "Prev Non-Friendly Target",
            [(int) LocString.NextTargetFriendly] = "Next Friendly Target",
            [(int) LocString.PrevTargetFriendly] = "Previous Friendly Target",
            [(int) LocString.TargCloseRed] = "Target Closest Murderer",
            [(int) LocString.TargCloseRedHumanoid] = "Target Closest Murderer Humanoid",
            [(int) LocString.TargCloseRedMonster] = "Target Closest Murderer Monster",
            [(int) LocString.TargCloseNFriend] = "Target Closest Non-Friendly",
            [(int) LocString.TargClosestNFriendlyHuman] = "Target Closest Non-Friendly Humanoid",
            [(int) LocString.TargClosestNFriendlyMonster] = "Target Closest Non-Friendly Monster",
            [(int) LocString.TargCloseFriend] = "Target Closest Friendly",
            [(int) LocString.TargClosestFriendlyHuman] = "Target Closest Friendly Humanoid",
            [(int) LocString.TargClosestFriendlyMonster] = "Target Closest Friendly Monster",
            [(int) LocString.TargCloseBlue] = "Target Closest Innocent",
            [(int) LocString.TargCloseInnocentHuman] = "Target Closest Innocent Humanoid",
            [(int) LocString.TargClosestInnocentMonster] = "Target Closest Innocent Monster",
            [(int) LocString.TargCloseGrey] = "Target Closest Grey",
            [(int) LocString.TargCloseGreyHuman] = "Target Closest Grey Humanoid",
            [(int) LocString.TargCloseGreyMonster] = "Target Closest Grey Monster",
            [(int) LocString.TargCloseCriminal] = "Target Closest Criminal",
            [(int) LocString.TargCloseCriminalHuman] = "Target Closest Criminal Humanoid",
            [(int) LocString.TargClosestCriminalMonster] = "Target Closest Criminal Monster",
            [(int) LocString.TargCloseEnemy] = "Target Closest Enemy",
            [(int) LocString.TargCloseEnemyHuman] = "Target Closest Enemy Humanoid",
            [(int) LocString.TargCloseEnemyMonster] = "Target Closest Enemy Monster",
            [(int) LocString.TargRandRed] = "Target Random Murderer",
            [(int) LocString.TargRandomRedHuman] = "Target Random Murderer Humanoid",
            [(int) LocString.TargRandomRedMonster] = "Target Random Murderer Monster",
            [(int) LocString.TargRandNFriend] = "Target Random Non-Friendly",
            [(int) LocString.TargRandomNFriendlyHuman] = "Target Random Non-Friendly Humanoid",
            [(int) LocString.TargRandomNFriendlyMonster] = "Target Random Non-Friendly Monster",
            [(int) LocString.TargRandFriend] = "Target Random Friendly",
            [(int) LocString.TargRandomFriendlyHuman] = "Target Random Friendly Humanoid",
            [(int) LocString.TargRandomFriendlyMonster] = "Target Random Friendly Monster",
            [(int) LocString.TargRandBlue] = "Target Random Innocent",
            [(int) LocString.TargRandInnocentHuman] = "Target Random Innocent Humanoid",
            [(int) LocString.TargRandomInnocentMonster] = "Target Random Innocent Monster",
            [(int) LocString.TargRandGrey] = "Target Random Grey",
            [(int) LocString.TargRandGreyHuman] = "Target Random Grey Humanoid",
            [(int) LocString.TargRandGreyMonster] = "Target Random Grey Monster",
            [(int) LocString.TargRandCriminal] = "Target Random Criminal",
            [(int) LocString.TargRandCriminalHuman] = "Target Random Criminal Humanoid",
            [(int) LocString.TargRandomCriminalMonster] = "Target Random Criminal Monster",
            [(int) LocString.TargRandEnemy] = "Target Random Enemy",
            [(int) LocString.TargRandEnemyHuman] = "Target Random Enemy Humanoid",
            [(int) LocString.TargRandEnemyMonster] = "Target Random Enemy Monster",
            [(int) LocString.NextTargetEnemyHumanoid] = "Next Enemy Humanoid Target",
            [(int) LocString.NextTargetCriminalHumanoid] = "Next Criminal Humanoid Target",
            [(int) LocString.NextTargetMurdererHumanoid] = "Next Murderer Humanoid Target",
            [(int) LocString.NextTargetInnocentHumanoid] = "Next Innocent Humanoid Target",
            [(int) LocString.NextTargetFriendlyHumanoid] = "Next Friendly Humanoid Target",
            [(int) LocString.NextTargetGreyHumanoid] = "Next Grey Humanoid Target",
            [(int) LocString.NextTargetNonFriendlyHumanoid] = "Next Non-Friendly Humanoid Target",
            [(int) LocString.NextTargetEnemyMonster] = "Next Enemy Monster Target",
            [(int) LocString.NextTargetCriminalMonster] = "Next Criminal Monster Target",
            [(int) LocString.NextTargetMurdererMonster] = "Next Murderer Monster Target",
            [(int) LocString.NextTargetInnocentMonster] = "Next Innocent Monster Target",
            [(int) LocString.NextTargetFriendlyMonster] = "Next Friendly Monster Target",
            [(int) LocString.NextTargetGreyMonster] = "Next Grey Monster Target",
            [(int) LocString.NextTargetNonFriendlyMonster] = "Next Non-Friendly Monster Target",
            [(int) LocString.PrevTargetEnemyHumanoid] = "Previous Enemy Humanoid Target",
            [(int) LocString.PrevTargetCriminalHumanoid] = "Previous Criminal Humanoid Target",
            [(int) LocString.PrevTargetMurdererHumanoid] = "Previous Murderer Humanoid Target",
            [(int) LocString.PrevTargetInnocentHumanoid] = "Previous Innocent Humanoid Target  ",
            [(int) LocString.PrevTargetFriendlyHumanoid] = "Previous Friendly Humanoid Target",
            [(int) LocString.PrevTargetGreyHumanoid] = "Previous Grey Humanoid Target",
            [(int) LocString.PrevTargetNonFriendlyHumanoid] = "Previous Non-Friendly Humanoid Target",
            [(int) LocString.PrevTargetEnemyMonster] = "Previous Enemy Monster Target",
            [(int) LocString.PrevTargetCriminalMonster] = "Previous Criminal Monster Target",
            [(int) LocString.PrevTargetMurdererMonster] = "Previous Murderer Monster Target",
            [(int) LocString.PrevTargetInnocentMonster] = "Previous Innocent Monster Target",
            [(int) LocString.PrevTargetFriendlyMonster] = "Previous Friendly Monster Target",
            [(int) LocString.PrevTargetGreyMonster] = "Previous Grey Monster Target",
            [(int) LocString.PrevTargetNonFriendlyMonster] = "Previous Non-Friendly Monster Target",
            [(int) LocString.CriminalTargets] = "> Criminal Targets",
            [(int) LocString.EnemyTargets] = "> Enemy Targets",
            [(int) LocString.FriendlyTargets] = "> Friendly Targets",
            [(int) LocString.GreyTargets] = "> Grey Targets",
            [(int) LocString.InnocentTargets] = "> Innocent Targets",
            [(int) LocString.MurdererTargets] = "> Murderer Targets",
            [(int) LocString.NonFriendlyTargets] = "> Non-Friendly Targets",
            [(int) LocString.Mysticism] = "Mysticism",
            [(int) LocString.Masteries] = "Masteries",
            [(int) LocString.SpellWeaving] = "Spellweaving",

            // Hotkey-Baum: Wurzel + Kategorien (1209 + HKCategory)
            [(int) LocString.HotKeys] = "Hot Keys",
            [(int) LocString.HotKeys + 1] = "Items",
            [(int) LocString.HotKeys + 2] = "Targets",
            [(int) LocString.HotKeys + 3] = "Agents",
            [(int) LocString.HotKeys + 4] = "Dress",
            [(int) LocString.HotKeys + 5] = "Macros",
            [(int) LocString.HotKeys + 6] = "Spells",
            [(int) LocString.HotKeys + 7] = "Skills",
            [(int) LocString.HotKeys + 8] = "Misc",
            [(int) LocString.HotKeys + 9] = "Friends",
            [(int) LocString.HotKeys + 10] = "Scripts"
        };

        /// <summary>
        /// Phase 3c2: Anzeigetexte fuer numerisch registrierte Hotkeys ausserhalb
        /// des LocString-Enums (Spell-/Skill-Clilocs wie 3002011/1044060+i).
        /// Razor CE loest diese ueber die Language-Packs bzw. spells.def auf;
        /// der Port traegt sie beim Registrieren hier ein. Reine Anzeige —
        /// die Profil-Identitaet ("L:&lt;id&gt;") haengt nur an der Nummer.
        /// </summary>
        public static void RegisterRuntime(int key, string text)
        {
            if (!string.IsNullOrEmpty(text))
                m_Enu[key] = text;
        }

        public static string GetString(LocString key)
        {
            return GetString((int) key);
        }

        public static string GetString(int key)
        {
            if (m_Enu.TryGetValue(key, out string text))
                return text;

            if (Enum.IsDefined(typeof(LocString), key))
                return ((LocString) key).ToString();

            return key.ToString();
        }

        public static string GetString(string key)
        {
            return key;
        }

        /// <summary>
        /// Stub: Cliloc-Aufloesung (Razor CE liest Cliloc.enu).
        /// TODO Phase 4: ueber IClientServices.GetCliloc anbinden.
        /// </summary>
        public static string GetCliloc(int key)
        {
            return string.Empty;
        }

        public static string Format(LocString key, params object[] args)
        {
            if (args == null || args.Length == 0)
                return GetString(key);

            if (m_Enu.TryGetValue((int) key, out string text))
            {
                try
                {
                    return string.Format(text, args);
                }
                catch
                {
                }
            }

            // Fallback wie der bisherige Stub: "Key: arg1, arg2"
            return $"{key}: {string.Join(", ", args)}";
        }
    }
}
